### ISSUE TITLE
migrate to vendor/ experiment

### ISSUE THREAD

**Issue by monstermunchkin** [SUSE/zypper-docker#100]
We're not testing nor using Go < 1.5 anymore, therefore we should use the vendor/ experiment which is also supported by Godeps.

**Comment by tboerger** [comment]
Please don't use godeps, use govend ;)

**Comment by mssola** [comment]
I'd say to use godeps because that's what we are already using :)

**Comment by tboerger** [comment]
Than switch to govend, you've got somebody with direct write access in-house and it's damn simple :D

**Comment by mssola** [comment]
I'd still pick godep because it's almost an "standard" in go development (everybody knows it, and know the basics of it), but I have no strong opinions. @flavio what do you think ?

**Comment by flavio** [comment]
I just played a bit with `govend`, I really like the idea of **not** checking out the code into by GOPATH and then copying it into the local `Godeps`. I would go for it right now.

However I don't think this is a urgent matter, we can leave the code as it is and wait a little to see how `govend` is going to evolve/be received by the Go community.

**Comment by cyphar** [comment]
Does `govend` let you specify a particular commit hash of the project you want to vendor? Godep doesn't let you specify it (when updating), and you have do some horrible stuff to get it to work.

**Comment by flavio** [comment]
I'm not sure if there's an easy way to do that, however it looks like it's just a matter of changing the `vendor.yml` file (see https://github.com/govend/govend#lock-packages)

**Comment by tboerger** [comment]
> Does govend let you specify a particular commit hash of the project you want to vendor? Godep doesn't let you specify it (when updating), and you have do some horrible stuff to get it to work.

At least you can specify that within the yml config, as an example: https://github.com/solderapp/solder-cli/blob/master/vendor.yml

**Comment by cyphar** [comment]
That sounds nice. How does it deal with flattening dependencies? Does it support dependencies that use `godep`?

**Comment by tboerger** [comment]
> That sounds nice. How does it deal with flattening dependencies? Does it support dependencies that use godep?

That's something I can't answer 100% sure. But I pinged @jackspirou, the main author, on Gitter to jump in and answer open questions :)

**Comment by jackspirou** [comment]
Hi @cyphar - `govend` has a `--prune` flag which follows the deptree and removes packages that are not actually used.  Also deps that use `godep` should not be an issue, but please let me know if you have a particular use-case/issue in mind.

**Comment by monstermunchkin** [comment]
I played around with `govend` as well and `govend`-ified `zypper-docker` for testing purposes. It's a really nice and clean solution, and I think we could/should replace Godep with it.
However, I also have a branch with the migration done using Godep, in case we should stick with it.

What do you guys think?

**Comment by mssola** [comment]
I'm fine with either godep or govend. What do the others think? :)

**Comment by tboerger** [comment]
> I'm fine with either godep or govend. What do the others think? :)

I like govend. @monstermunchkin already mentioned the 2 different branches so you can directly compare the behavior of godep and govend.

**Comment by flavio** [comment]
Let's go with `govend`. @tboerger would you like to create a package for it on devel:language:go ? :D

**Comment by tboerger** [comment]
> Let's go with govend. @tboerger would you like to create a package for it on devel:language:go ? :D

Can do that :)
