### ISSUE TITLE
--severity flag does not handle well when no image was specified

### ISSUE THREAD

**Issue by mssola** [SUSE/zypper-docker#106]
Executing:

    $ zypper-docker lp --severity moderate

Gives the following output:

    Error response from daemon: Container command not found or does not exist.

Expected output:

    Error: no image name specified.

Which is the same as for the other flags.

**Comment by flavio** [comment]
We should fix that before releasing zypper-docker

**Comment by mssola** [comment]
@flavio agreed, @monstermunchkin is working on it :wink:
