### ISSUE TITLE
severity checking for images with zypper < 1.12.6

### ISSUE THREAD

**Issue by monstermunchkin** [SUSE/zypper-docker#108]
Hello,

at the moment, there is no way of listing / filtering patches by severity (`--severity` flag) for images running an older version (< 1.12.6) of `zypper`. The information regarding the severity however is present when running `zypper lp`.

If the `--severity` flag functionality is needed regardless of the version, one has to do some scripting and parse the output of `zypper lp` which is not the end of the world.

However, it would be possible for `zypper-docker` to detect an older version (which it already does) and simply deal with it instead of failing (which it currently does). On the other hand, `zypper-docker` itself is a wrapper around `zypper`, and introducing flags which aren't actually supported by the `zypper` version might not be cool.

What are your thoughts on this? Could something go seriously wrong if it were to be implemented?

/cc @inercia @cyphar @flavio @jordimassaguerpla @mssola

**Comment by jordimassaguerpla** [comment]
I think it would be a nice feature to have, so I vote "yes" ;)

**Comment by cyphar** [comment]
As long as the output of `zypper` is stable and has the same results as the later version, I think it'd be a nice feature to add support for older `zypper` versions. :D

**Comment by mssola** [comment]
It would be a nice feature indeed. I'd say that it's ok to provide the `--severity` flag regardless if the zypper to be run supports it or not. This would be just an implementation detail hidden from the user :wink:

**Comment by flavio** [comment]
This is a nice idea, I would say this has however a low priority on our roadmap

**Comment by mbtamuli** [comment]
I would like to try to tackle this issue.

**Comment by mssola** [comment]
@mbtamuli sure, feel free 👍

**Comment by skriesch** [comment]
I'm interested for GSoC, too. I'll try this issue.

**Comment by chawlanikhil24** [comment]
@mssola  I am interested to pursue this issue for GSoC. Hope it's fine?

**Comment by mssola** [comment]
Sure, go ahead

**Comment by flavio** [comment]
I just checked, this is still an issue with sles11sp4 (comes with zypper `1.6.327`)

**Comment by flavio** [comment]
SLE12 SP2 has the right version of zypper. @mssola, @vrothberg and I discussed this issue and decided to reduce the scope of it to the following: check the version of zypper inside of a docker image and, if the version is too old, show a warning message and exit with an error. The reasoning is that sle11sp4 is sooner of later going to be discontinued (31st March 2020).

**Comment by lightlace** [comment]
@monstermunchkin you said: However, it would be possible for zypper-docker to detect an older version (which it already does) and simply deal with it instead of failing (which it currently does). 

I have a sles11sp4 docker image and it has zypper version 1.6.327.
When i execute 'zypper-docker lp suse7sles11sp4' it lists all the patches and does not fail.
Is this the right behavior?

**Comment by monstermunchkin** [comment]
@lightlace That is the right behaviour, but this issue is a different one. `zypper` < 1.12.6 doesn't support the `--severity` flag, and `zypper-docker` will fail if you provide it. However, AFAIR the output of `zypper lp` still shows the severity.
What we'd like here is `zypper-docker` to support the `--severity` flag regardless of the version. That means, if the flag is not supported by the zypper version, we need to parse the output and filter manually.

**Comment by vrothberg** [comment]
@monstermunchkin, @lightlace There have been some planned changes for this issue (see comment above). The idea was to reduce the scope to only support docker >= 1.12.6 and show an error message otherwise.

>SLE12 SP2 has the right version of zypper. @mssola, @vrothberg and I discussed this issue and decided to reduce the scope of it to the following: check the version of zypper inside of a docker image and, if the version is too old, show a warning message and exit with an error. The reasoning is that sle11sp4 is sooner of later going to be discontinued (31st March 2020).

**Comment by lightlace** [comment]
@vrothberg: I think, we have this already implemented.
When i try to run `zypper-docker lp --severity important suse/sles11sp4`, it says: `the --severity flag is only available for zypper versions >= 1.12.6`.

Or am i wrong?

**Comment by vrothberg** [comment]
@lightlace You're right! Feel free to close : )

**Comment by lightlace** [comment]
Okay, just as @vrothberg confirmed, we already have a implementation in patches.go, which tells the user that the severity flag is only available for zypper versions >= 1.12.6.

Therefore this issue can be closed.
