### ISSUE TITLE
zypper-docker list-updates dockerimage takes to container-suseconnect not to my suse manager spacewalk service

### ISSUE THREAD

**Issue by arjunm183** [SUSE/zypper-docker#109]
Hello Team,

We have a suse manager and i wanted to make sure my docker images which are built using sles12 docker base image needs to be patched properly. I wanted to make sure that zypper-docker contacts my spacewalk service linked with SUSE Manager. 

Can you help me.

Regards,
Arjun.M

**Comment by flavio** [comment]
This is a known issue. We are currently working together with the SUSE Manager team to find a solution that will allow [container-suseconnect](https://github.com/SUSE/container-suseconnect) to get the repositories from a SUSE Manager instance.

This will automatically make zypper-docker work.
