### ISSUE TITLE
move away from deprecated engine-api

### ISSUE THREAD

**Issue by PI-Victor** [SUSE/zypper-docker#113]
Docker deprecated the engine-api https://github.com/docker/engine-api#deprecated 
It's now a part of docker (again) https://github.com/docker/docker/tree/master/api#working-on-the-engine-api
Though i have a sneaky feeling that means updating the whole docker vendor tree :-/
Thoughts?

**Comment by PI-Victor** [comment]
also the client is now here. https://github.com/docker/docker/tree/master/client

**Comment by mssola** [comment]
Sigh ... It would be better to move to the new client whenever we anticipate that some API is going to get broken, etc. It should be fine for now, but if you provide a PR and all tests continue to pass, I'm ok with it.

**Comment by PI-Victor** [comment]
true that. i want to see what other priorities we have in the upcoming days before this and then i'll try to tackle it later.

**Comment by cyphar** [comment]
T_T
