### ISSUE TITLE
Build Failing in "make build"

### ISSUE THREAD

**Issue by chawlanikhil24** [SUSE/zypper-docker#115]
In the corresponding Dockerfile, I am facing the following error:

`Building zypper-docker

docker build -f docker/Dockerfile -t zypper-docker docker

Sending build context to Docker daemon 8.192 kB

Step 1/16 : FROM golang
 ---> 9ad50708c1cb

Step 2/16 : RUN go get golang.org/x/tools/cmd/cover
 ---> Using cache
 ---> 34cf04cf0a71

Step 3/16 : RUN go get golang.org/x/tools/cmd/vet
 ---> Running in 0c15b5215c5a
package golang.org/x/tools/cmd/vet: cannot find package "golang.org/x/tools/cmd/vet" in any of:
	/usr/local/go/src/golang.org/x/tools/cmd/vet (from $GOROOT)
	/go/src/golang.org/x/tools/cmd/vet (from $GOPATH)

The command '/bin/sh -c go get golang.org/x/tools/cmd/vet' returned a non-zero code: 1
Makefile:60: recipe for target 'build' failed
make: *** [build] Error 1
`

And when I checked  [this](https://golang.org/x/tools/cmd/vet) used at this step, I got "No Such Url exists".

**Comment by mssola** [comment]
Fixed with #116
