### ISSUE TITLE
Update Dockerfiles and tests

### ISSUE THREAD

**Issue by vrothberg** [SUSE/zypper-docker#119]
Move away from 13.2 and update to use more recent version of openSUSE.

- [x] update travis file
- [x] update Dockerfiles
- [x] update tests

**Comment by vrothberg** [comment]
The Dockerfiles and travis are updated now, but the tests need to changed to reflect that. `test_integration` is currently disabled until the issue has been solved. I am therefore changing the title.

**Comment by vrothberg** [comment]
Dockerfiles and Travis have been updated in https://github.com/SUSE/zypper-docker/pull/118

**Comment by vrothberg** [comment]
Regarding the tests, @mssola, @lightlace and I came up with the following idea. In order to avoid a situation where either the image or the repositories are not available anymore, we need to control both the image and the zypper repository. Hence, our idea is to use an older image (e.g., Leap 42.2) and prepare a dedicated repository with some newer packages (e.g., openssl or image magic).

The proposed steps can be summarized as follows:

**1.** Push an outdated image to a publically reachable repository where it won't be removed. This implies we have control over the image repository.

**2.** Create a dedicated zypper repository with a selected set of packages that update the image from step (1).

**3.** Create a new image based on the one from step (1) which includes the repository from step (2).

@flavio, what do you think?

**Comment by flavio** [comment]
I like the idea. Why don't you simply push an outdated image with the custom repository already added? By doing that you would achieve the same goal with less steps

**Comment by vrothberg** [comment]
> I like the idea. Why don't you simply push an outdated image with the custom repository already added? By doing that you would achieve the same goal with less steps

Oh, yes, this step was missing. So there's another step (4) to push the updated image as well to the image repository.

**Comment by lightlace** [comment]
Little status update from my side:

I created a docker image based on 42.2, and made a local repo consisting of ImageMagick and openSSL inside the image. Besides that, i removed all repositories whihc come with 42.2, in order to not get any further updates.

Has anyone from you any further suggestions?

**Comment by lightlace** [comment]
another status update: had a conversation with darix, and he said, that it might be difficult to get a proper output of "zypper list-patches", when we only have the custom repository.
Therefore, i concentrate on integrating 'zypper list-updates' into the test.

**Comment by vrothberg** [comment]
> Therefore, i concentrate on integrating 'zypper list-updates' into the test.

Sounds good to me. @flavio, @cyphar, @mssola - Do you have an idea how to get patch information into a local repository?

**Comment by lightlace** [comment]
Status Update Nr. 3:
I integrated the docker image into the "update_test.go" and it passes. One down, more to go.

**Comment by flavio** [comment]
I don't know about how to have patches on a custom repository. Can you talk with someone from the SUSE Manager team (Michael Calmer for example), they definitely have experience in this area.

**Comment by vrothberg** [comment]
@parlt91 has done a great job on finishing the remaining tasks. I consider this issue to be resolved.
