### ISSUE TITLE
Instruct travis to perform daily builds

### ISSUE THREAD

**Issue by flavio** [SUSE/zypper-docker#121]
We should use a new (?) Travis feature that allows builds to be triggered on a daily/weekly basis even when no PR are submitted. This would allow us to keep the health status of the project monitored in a better way.

**Comment by lightlace** [comment]
There is a feature called "Cron Jobs".
I've created a fork of zypper-docker and created a Cron Job for Travis, so that he builds zypper-docker daily.
When i have some results, i will share it here with you.

**Comment by cyphar** [comment]
I just checked the settings, and we have added daily "cron job" set up to run Travis once a day. Closing.

**Comment by lightlace** [comment]
@cyphar I added the 'cron job' just as an experiment yesterday.
Maybe we should wait for some daily build results if it does the job correctly and then close the issue.

**Comment by cyphar** [comment]
@lightlace Ah sorry, I misunderstood. 😸

**Comment by lightlace** [comment]
seems like Travis really does well with the daily builds.
So this issue can be closed.
