### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by vrothberg** [SUSE/zypper-docker#124]
This is a vote for preparing a new release for zypper-docker.

Since 1.2.0, eleven commits [1] have been merged. Although most are related to fixing the build and CI, there is some user-visible changes related to passing the exit codes from zypper to zypper-docker, so that zypper-docker now returns zyppers exit codes (see bsc#1018823).

As the API has changed regarding exit codes, I suggest to jump to a next major version **2.0.0**.

[1] https://github.com/SUSE/zypper-docker/compare/v1.2.0...master

**Comment by mssola** [comment]
I wanted to do this once I got to merge my infamous `cli-separation` branch, but I never got the time to finish it 😓 So there are two options:

1. I give more priority to finish the `cli-separation` branch (which would be cool for example for Portus' new security scanning support), and we bundle everything into the 2.0.0 branch.
2. We release 2.0.0 and whenever I resume back my work on that branch and merge it, we tag a 3.0.0 release.

My rationale is that the `cli-separation` branch has quite some heavy changes that affect the API and the UI. Thus, this change alone deserves a major version on its own. That being said, next week I go for vacations, so if this is really urgent, I agree to release a new version now, and take the second option.

What do you think ?

**Comment by flavio** [comment]
I would prefer to have more fixes done before releasing the next version. The most important fix would be fixing the CI tests.

I propose to create a milestone for the 2.0 release and add all the issues/features to ship with it inside of it.

Note well: a trainee is going to join during September, I think it would be really nice for him to be involved with fixing these issues and see his work get out into a release.
