### ISSUE TITLE
SMT: how to pass certificate?

### ISSUE THREAD

**Issue by vrothberg** [SUSE/zypper-docker#129]
bsc#1026595 describes problems with `zypper-docker` when the CA used by the SMT server is not trusted in an image.

One solution is to mount the CA on-demand as a volume. This should be considered as a safe operation as volume-data won't be committed to a new image.

To me bsc#1026595 sounds like a rather special use-case for which we can provide a general solution by adding an option to `zypper-docker` to add additional arguments to `zypper`, for instance, `--additional-args`.

**Edit:** For sure I meant that the additional args are passed to Docker, so an option like `--docker-args` might be more appropriate.

**Comment by cyphar** [comment]
Isn't this something that should be done by our SUSEConnect setup? In particular, shouldn't we include CAs in the `/run/secret` that we pull from the host?

**Comment by flavio** [comment]
I would prefer to have a dedicated option of zypper-docker to handle this case. Something really specific that makes it obvious what is the purpose of it. I'm thinking about something like `--use-host-trusted-certificates` that would mount the host certificates into the image as read-only volume.

However I'm not convinced we should do that (or even close the linked bug). Security is a delicate topic and automation can introduce weaknesses or unexpected side effects. I would prefer not to solve this issue and let the client add his own certificates into the base images as we are currently recommending.

**Comment by vrothberg** [comment]
Sounds good to me! I am closing this issue then
