### ISSUE TITLE
Use `gimme` to test zypper-docker with different golang versions

### ISSUE THREAD

**Issue by mssola** [SUSE/zypper-docker#39]
Currently we have a Docker image for each image that we want to test. This can be a bit awkward in the future. My proposal is to have just one Dockerfile, that uses [gimme](https://github.com/travis-ci/gimme). This is what Travis does to handle Go versions, and I think that is a good idea.

@flavio what do you think?

**Comment by flavio** [comment]
Looks interesting, however in don't think we are going to support more then 2 versions of go. We will have to focus only on what is actually used by us to build our RPMs and the next version.

I think this issue has a really low priority.

**Comment by mssola** [comment]
@flavio I'd say that we should support Go 1.4 onwards, since it's the version available in opensuse 13.2. Since Go 1.5 has been released, 1.4, 1.5 and tip should be tested. With `gimme` we would avoid things like the PR #38 :)

**Comment by mssola** [comment]
I agree that it has a low priority.
