### ISSUE TITLE
About "USERNAME" in the update command

### ISSUE THREAD

**Issue by mssola** [SUSE/zypper-docker#55]
I think we don't use it, and we use the current user instead. If this is the case, then the value should be removed from `flags.go`. Otherwise, we should removed "USERNAME" to "ZYPPER_DOCKER_USERNAME".

**Comment by flavio** [comment]
The `USERNAME` env variable is automatically used to initialize the `author` value. This env variable is always set by bash; that's why I picked it. I'm not so sure we should rename it

**Comment by mssola** [comment]
Commit 357a44c1c73b3b56023fe1a07e9fc6c449d05b9a fixes this issue
