### ISSUE TITLE
Add `--severity` flag to `list-patches`

### ISSUE THREAD

**Issue by flavio** [SUSE/zypper-docker#70]
Recent versions of zypper support also the `--severity` flag to filter the available patches.

*Note well:* this feature is not available with older releases of zypper, hence we have to handle that properly

**Comment by monstermunchkin** [comment]
How exactly should older versions be handled? It simply fails with "Unknown option --severity" which is OK, or not? There could however be an info message if one uses the flag, e.g. "Note that --severity is only available for zypper 1.12.6 and above."
Checking the zypper version from the container would be unnecessary IMHO and require a function (just for this case) to return the container's stdout.

Any thoughts?

**Comment by flavio** [comment]
What happens when you use this flag on an older release of zypper? I guess this will exit with an error, right?

**Comment by mssola** [comment]
I don't think printing the warning is needed here, as we assume that users know what they're doing. If they don't, then the command will fail and we can check whether there is in the error message the string: "Unknown option --severity", and output the warning: "ERROR: the --severity flag is only available for zypper versions >= 1.12.6".

We should also add this note in the man pages and in the usage string.

**Comment by monstermunchkin** [comment]
Which error message exactly do you mean? The string "Unknown option --severity" unfortunately is only printed to stdout and not to be seen in any (separate) error message.

**Comment by mssola** [comment]
Isn't there a way to capture the output from the container ? Or a way to determine the exact error ?

**Comment by monstermunchkin** [comment]
Not at the moment, although I have changed some functions which enable me to do that now.  What I also have done, is actually call `zypper --version` (only if `--severity` is used) to determine the version. The advantage is that it fails fast (no prior call to `zypper ref`) and the user gets nothing more than a meaningful error message.

**Comment by flavio** [comment]
> I don't think printing the warning is needed here, as we assume that users know what they're doing.

I bet to differ. A user might be inspecting an image built by someone else, hence he would not know which version of zypper is available in there.

What about:
  * when the severity flag is being used we look at the version of zypper inside of the container. this would be a dedicated docker run.
  * if the version of zypper is the right one we just execute the command
  * if the version is not the right one we print a warning and stop

The result of the check performed by the 1st step should be stored inside of our local cache (the one that already holds information about the openSUSE/SUSE images), so that it's not executed again

**Comment by mssola** [comment]
Sounds good to me.

**Comment by cyphar** [comment]
@jordimassaguerpla We can probably use this to clean up the failing Jenkins builds.
