### ISSUE TITLE
Allow users to attach to the stdin of the running container

### ISSUE THREAD

**Issue by mssola** [SUSE/zypper-docker#73]
It would be nice from a user point of view to attach to one of the containers spawned by zypper-docker and interact with it.

**Comment by vrothberg** [comment]
Is this still a feature you'd like to have? 

In case yes, I have some questions to discuss a potential design:
- Could you elaborate on a use-case for it?
- Why not use `docker run -it $image bash`?
- At which point would we attach? Before or after a command? Only in case of errors?

**Comment by mssola** [comment]
If I recall correctly this was proposed in cases where zypper asks for some user's input on some special cases. Not sure if it makes sense to be honest.

**Comment by flavio** [comment]
> Not sure if it makes sense to be honest.

+1. Closing, we can always reopen that if needed
