### ISSUE TITLE
Image-CMD deleted after zypper-docker update/patch

### ISSUE THREAD

**Issue by urban-it-solutions** [SUSE/zypper-docker#75]
After the zypper-docker update oder patch-command, the original CMD of the Image is deleted.
Before:
docker inspect sles12-java8-tomcat8 | grep CMD
            "#(nop) CMD [\"/bin/sh\" \"-c\" \"source /etc/sysconfig/tomcat-default \u0026\u0026 su $TOMCAT_OWNER -c \\\"$CATALINA_HOME/bin/catalina.sh run \\\"\"]"
After:
linux-bqo8:~ # docker inspect sles12-java8-tomcat8-patch_2015-11-11b | grep -b1 -i CMD
       "Cmd": [
            "zypper --non-interactive ref \u0026\u0026 zypper --non-interactive -n patch"

**Comment by flavio** [comment]
Which version of zypper-docker are you using?

**Comment by urban-it-solutions** [comment]
zypper-docker-1.1.0-1.1.x86_64
 

> Flavio Castelli <notifications@github.com> hat am 16. November 2015 um 14:55
> geschrieben:
> 
> 
>  Which version of zypper-docker are you using?
> 
>  —
>  Reply to this email directly or view it on GitHub
> <https://github.com/SUSE/zypper-docker/issues/75#issuecomment-157033841> .
> 
>   
> 

 
--
Axel Urban
Urban IT Solutions
Rögenweg 42
22359 Hamburg
Fon: 040-2286 2387
www.urban-its.de

**Comment by mssola** [comment]
I can also reproduce this. Working on it.
