### ISSUE TITLE
output image ignores namespace

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/zypper-docker#86]
run
zypper docker patch suse/sles11sp4:latest suse/sles11sp4:patched

and the output image will be

sles11sp4:patched

while I should have expected to be

suse/sles11sp4:patched

**Comment by mssola** [comment]
I cannot reproduce this. Which version are you using ?

**Comment by jordimassaguerpla** [comment]
zypper docker 1.1.1

**Comment by mssola** [comment]
@jordimassaguerpla could you try for 1.1.2? Maybe this has been fixed with b18b44349bbd4108945bfe5af6ac85a734cf69ab

**Comment by jordimassaguerpla** [comment]
@mssola : yes it has been fixed in 1.1.2
